# Generated by Django 4.0.5 on 2022-07-13 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passive', models.ImageField(upload_to='')),
                ('q', models.ImageField(upload_to='')),
                ('w', models.ImageField(upload_to='')),
                ('e', models.ImageField(upload_to='')),
                ('r', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField()),
                ('hp_per_level', models.IntegerField()),
                ('mp', models.IntegerField()),
                ('mp_per_level', models.IntegerField()),
                ('move_speed', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('armor_per_level', models.IntegerField()),
                ('spell_block', models.IntegerField()),
                ('spell_block_per_level', models.IntegerField()),
                ('attack_range', models.IntegerField()),
                ('hp_regen', models.IntegerField()),
                ('hp_regen_per_level', models.IntegerField()),
                ('mp_regen', models.IntegerField()),
                ('mp_regen_per_level', models.IntegerField()),
                ('attack_damage', models.IntegerField()),
                ('attack_damage_per_level', models.IntegerField()),
                ('attack_speed_per_level', models.IntegerField()),
                ('attack_speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('title', models.TextField(max_length=300)),
                ('blurb', models.TextField()),
                ('partype', models.CharField(max_length=25)),
                ('selfie', models.ImageField(upload_to='')),
                ('champion_id', models.IntegerField()),
                ('abilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lore.ability')),
                ('stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lore.stats')),
                ('tags', models.ManyToManyField(to='lore.tag')),
            ],
        ),
    ]
