# Generated by Django 4.0.5 on 2022-07-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0004_alter_stats_armor_alter_stats_armor_per_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='champion_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
