# Generated by Django 4.0.5 on 2022-07-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0006_remove_champion_abilities_delete_ability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='selfie',
        ),
    ]
