# Generated by Django 4.0.5 on 2022-07-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0007_remove_champion_selfie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name_plural': 'Stats'},
        ),
        migrations.AddField(
            model_name='champion',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
