# Generated by Django 4.0.5 on 2022-07-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0008_alter_stats_options_champion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
