# Generated by Django 4.0.5 on 2022-07-15 23:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0009_alter_champion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid1, max_length=100, unique=True),
        ),
    ]
