# Generated by Django 4.0.5 on 2022-07-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0011_alter_champion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='lore',
            field=models.TextField(null=True),
        ),
    ]
