# Generated by Django 4.0.5 on 2022-07-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0012_champion_lore'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='allytips',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='champion',
            name='enemytips',
            field=models.TextField(null=True),
        ),
    ]
