# Generated by Django 4.0.5 on 2022-07-18 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0014_tip_remove_champion_allytips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='tip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lore.tip'),
        ),
    ]
