# Generated by Django 4.0.5 on 2022-07-18 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lore', '0015_champion_tip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('allytips', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EnemyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('enemytips', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='champion',
            name='tip',
        ),
        migrations.DeleteModel(
            name='Tip',
        ),
        migrations.AddField(
            model_name='champion',
            name='allytip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lore.allytip'),
        ),
        migrations.AddField(
            model_name='champion',
            name='enemytips',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lore.enemytip'),
        ),
    ]
