# Generated by Django 4.0.5 on 2022-07-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_name', models.CharField(max_length=50)),
                ('summoner_level', models.IntegerField()),
                ('profileIconId', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('encryptedSummonerId', models.CharField(max_length=150)),
            ],
        ),
    ]
